//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectorQualification
    {
        public int ID { get; set; }
        public int DirectorID { get; set; }
        public int QualificationID { get; set; }
    
        public virtual DirectorName1 DirectorName1 { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
