//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DirectorName1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DirectorName1()
        {
            this.DirectorQualifications = new HashSet<DirectorQualification>();
        }
    
        public int DirectorID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Provide Surname")]  
        [StringLength(20, MinimumLength = 5, ErrorMessage = "Surname Should be min 5 and max 20 length")]
        public string Surname { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Provide Initials")]
        [StringLength(5, MinimumLength = 1, ErrorMessage = "Initials Should atleats be min 1 and max 5 length")]
        public string Initials { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Provide First Name")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "First Name Should be min 5 and max 20 length")]
        public string FirstName { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Select Title")]
        //[StringLength(20, ErrorMessage = "First Name Should be min 5 and max 20 length")]
        public string Title { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Provide Year of Birth")]
        [Range(1,2017, ErrorMessage ="Year of birth can't be less than 1 or more than the current year")]
        public int YearOfBirth { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage ="Select gender")]
        public string Gender { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Select Group type")]
        public int Grouping { get; set; }

        public string Profile { get; set; }

        public System.DateTime UpdateDate { get; set; }
    
        public virtual Grouping Grouping1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DirectorQualification> DirectorQualifications { get; set; }
    }
}
